### ISSUE TITLE
Feature Request: Create a Startpoint, connecting with Endpoint

### ISSUE THREAD

**Issue by WeltensiedlerDE** [GorgeousOne/TangledMazes#16]
Hello, really nice plugin. I love it. But I'm missing a little bit. I tried to create a Maze with an Endingzone in the middle. So far so good. Creating a Maze Cut out the Middle of the Maze and then I have created 8 Endpoints. But these Endpoint are all connected with each other.

I tried to create a Team-Maze. 4 Teams, 4 Startpoint and 1 Goal. Some passages between the the walls to other teams are okay, but it's a little confusing, that each Endpoint connects with all other.

And then another Problem! I defined a Pathwidth of 5 Blocks and a Wallwidth of 1 Block. I have make a blueprint on the ground and I hoped, that all walls are on the right position. But some walls are thicker than 1 block and so the walls are moved.

Is it possible to fix this, so the walls are all in the right position? The walls should be on the red lined or in a square to it.

![Screenshot_2](https://user-images.githubusercontent.com/10679451/61977696-6bac2880-afef-11e9-942e-ae811a994158.png)

**Comment by WeltensiedlerDE** [comment]
And the yellow concrete are the start- and endpoints. Is it possible to make these centered?

**Comment by GorgeousOne** [comment]
Hello Tomcatchriss,
nice to hear that you like to plugin. But I am not sure if I can change anything about the behaviours  that occur here.

Regarding the problem with the end points:
I implemented the maze generation in a way that a maze has to connect all it's exits to each other. In my eyes (or the eyes of the plugin) you want to create here 4 seperate mazes with one entrance - the start point - and one exit - the end point.
For me it still seems like the most convenient way to leave the maze algorithm how it is right now. If you think there is a more simply and comprehensible technique for connecting exits we can talk about that.

Regarding the problem with the wall width:
You can see that in at the maze stays on the red lines near the exit pointing down (probably your main exit). The walls in the other sectors did not move but your red layout moved since the size of your goal area in the middle is not according to the maze's layout.
There is no reasonable way how I could tell the plugin when to make paths how long at which point. The only way is to tell the maze to stay in it's grid made of wall width and path width. I am sorry if that is not fitting for you, but you would need to change the size of the middle for exmaple.


Maze exits are always built to the right side when you look from the outside. You can center the exits by moving your yellow concrete blocks a little bit to the left.

I hope I could help you with this answer. I can understand if this sounds a bit frustrating but it is mostly very difficult to explain to a computer what you want to achieve individually, therefore also this plugin will have it's limits.

Have a nice day
GorgeousOne
